 #Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  build-test-deploy:

    # A list of available CircleCI Docker Convenience Images is available here:
    # https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:19.0

    working_directory: ~/repo/Section_16/mb2g-release-plugin-circleci

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      # Checkout the code as the first step.
      - checkout:
          path: ~/repo

      # Download and cache dependencies, if any
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline

      # Cache dependencies for future runs
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

       # Run the integration Tests.
      - run:
          name: Build & Test
          command: mvn integration-test

      - run:
          name: Deploy to packagecloud
          command: mvn deploy -s ./settings.xml

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  deploy:
    jobs:
      - build-test-deploy