 #Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1
jobs:
  build-release:

    # A list of available CircleCI Docker Convenience Images is available here:
    # https://circleci.com/developer/images/image/cimg/openjdk
    docker:
      - image: cimg/openjdk:19.0

    working_directory: ~/repo/Section_16/mb2g-release-plugin-circleci

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      # this enables colors in the output
      TERM: xterm

    steps:
      # GitHub Read/Write access: use CircleCI User Key (read/write) deployment key
      - add_ssh_keys:
          fingerprints:
            - "70:32:cb:b4:2f:f2:4a:5c:54:56:18:1a:7d:65:2e:4e"

      # Checkout the code as the first step.
      - checkout:
          path: ~/repo

      # Download and cache dependencies, if any
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "pom.xml" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Download Dependencies
          command: mvn dependency:go-offline

      # Cache dependencies for future runs
      - save_cache:
          key: v1-dependencies-{{ checksum "pom.xml" }}
          paths:
            - ~/.m2

      - run:
          name: Update git configuration
          command: |
            git config user.email "cpp.sage@gmail.com"
            git config user.name "Via CircleCI Build"

      - run:
          name: Release to PackageCloud
          command: mvn --batch-mode release:prepare release:perform -s ./settings.xml

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  release:
    jobs:
      - build-release
